name: Test build CI (linux amd64 + arm64)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  build-amd64:
    uses: ./.github/workflows/generate_binaries_linux.yml
    with:
      arch: amd64

  build-arm64:
    uses: ./.github/workflows/generate_binaries_linux.yml
    with:
      arch: arm64
